// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatDoYouMeme.Api.Data;

#nullable disable

namespace WhatDoYouMeme.Api.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20260801131736_AddSelectedCaptionToRound")]
    partial class AddSelectedCaptionToRound
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("WhatDoYouMeme.Api.Models.Caption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RoundId", "PlayerId")
                        .IsUnique();

                    b.ToTable("Captions");
                });

            modelBuilder.Entity("WhatDoYouMeme.Api.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("WhatDoYouMeme.Api.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("WhatDoYouMeme.Api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WhatDoYouMeme.Api.Models.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JudgeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedCaptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinningCaptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ImageId");

                    b.HasIndex("JudgeId");

                    b.HasIndex("SelectedCaptionId");

                    b.HasIndex("WinnerId");

                    b.HasIndex("WinningCaptionId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("WhatDoYouMeme.Api.Models.Caption", b =>
                {
                    b.HasOne("WhatDoYouMeme.Api.Models.Player", "Player")
                        .WithMany("Captions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatDoYouMeme.Api.Models.Round", "Round")
                        .WithMany("Captions")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("WhatDoYouMeme.Api.Models.Image", b =>
                {
                    b.HasOne("WhatDoYouMeme.Api.Models.Game", "Game")
                        .WithMany("Images")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("WhatDoYouMeme.Api.Models.Player", b =>
                {
                    b.HasOne("WhatDoYouMeme.Api.Models.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("WhatDoYouMeme.Api.Models.Round", b =>
                {
                    b.HasOne("WhatDoYouMeme.Api.Models.Game", "Game")
                        .WithMany("Rounds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatDoYouMeme.Api.Models.Image", "Image")
                        .WithMany("Rounds")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WhatDoYouMeme.Api.Models.Player", "Judge")
                        .WithMany()
                        .HasForeignKey("JudgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WhatDoYouMeme.Api.Models.Caption", "SelectedCaption")
                        .WithMany()
                        .HasForeignKey("SelectedCaptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WhatDoYouMeme.Api.Models.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WhatDoYouMeme.Api.Models.Caption", "WinningCaption")
                        .WithMany()
                        .HasForeignKey("WinningCaptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Game");

                    b.Navigation("Image");

                    b.Navigation("Judge");

                    b.Navigation("SelectedCaption");

                    b.Navigation("Winner");

                    b.Navigation("WinningCaption");
                });

            modelBuilder.Entity("WhatDoYouMeme.Api.Models.Game", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Players");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("WhatDoYouMeme.Api.Models.Image", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("WhatDoYouMeme.Api.Models.Player", b =>
                {
                    b.Navigation("Captions");
                });

            modelBuilder.Entity("WhatDoYouMeme.Api.Models.Round", b =>
                {
                    b.Navigation("Captions");
                });
#pragma warning restore 612, 618
        }
    }
}
